# ==============================================================================
# EmbedFile.cmake - Converte arquivo binário em array C++
# ==============================================================================
# Uso via -P (script mode):
#   cmake -DINPUT_FILE=<path> -DOUTPUT_FILE=<path> -DSYMBOL=<name> -P EmbedFile.cmake
#
# Gera um .cpp contendo:
#   namespace embedded {
#       alignas(16) const unsigned char SYMBOL_data[] = { ... , 0x00 };
#       const std::size_t SYMBOL_size = sizeof(SYMBOL_data) - 1;
#       const char* SYMBOL_str() { return ...; }
#   }
# ==============================================================================

cmake_minimum_required(VERSION 3.16)

# Validação dos parâmetros (só executa em script mode)
if(DEFINED INPUT_FILE AND DEFINED OUTPUT_FILE)
    if(NOT DEFINED SYMBOL)
        set(SYMBOL "embedded_data")
    endif()

    # Lê o arquivo em hexadecimal
    file(READ "${INPUT_FILE}" hex_data HEX)

    # Calcula o tamanho original (cada byte = 2 chars hex)
    string(LENGTH "${hex_data}" hex_len)
    math(EXPR file_size "${hex_len} / 2")

    # Converte "abcd..." -> "0xab, 0xcd, ..."
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " formatted_hex "${hex_data}")

    # Remove a vírgula e espaço finais
    string(REGEX REPLACE ", $" "" formatted_hex "${formatted_hex}")

    # Quebra em linhas de ~12 bytes para legibilidade
    string(REGEX REPLACE "([^,]+, [^,]+, [^,]+, [^,]+, [^,]+, [^,]+, [^,]+, [^,]+, [^,]+, [^,]+, [^,]+, [^,]+,) " "\\1\n    " formatted_hex "${formatted_hex}")

    # Garante que o diretório de saída existe
    get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}")

    # Gera o conteúdo - note: evitamos [[ ]] pois CMake interpreta como bracket argument
    set(ATTR_MAYBE_UNUSED "[[maybe_unused]]")
    
    file(WRITE "${OUTPUT_FILE}" 
"// Auto-generated from: ${INPUT_FILE}
// Generated by CMake EmbedFile.cmake - DO NOT EDIT
// Size: ${file_size} bytes
#include <cstddef>

namespace embedded {

alignas(16) const unsigned char ${SYMBOL}_data[] = {
    ${formatted_hex}, 0x00
};

${ATTR_MAYBE_UNUSED} const std::size_t ${SYMBOL}_size = sizeof(${SYMBOL}_data) - 1;

const char* ${SYMBOL}_str() {
    return reinterpret_cast<const char*>(${SYMBOL}_data);
}

} // namespace embedded
")

    message(STATUS "Embedded: ${INPUT_FILE} -> ${OUTPUT_FILE} (${file_size} bytes)")
endif()
